//
// Module TINER_Vlog.TIMER_tb.struct
//
// Created:
//          by - User.UNKNOWN (VBOX)
//          at - 00:26:36 05.05.2019
//
// Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
//

`resetall
`timescale 1ns/10ps
module TIMER_tb;


// Internal Declarations



// Local declarations

// Internal signal declarations
wire       alarm;
wire       clk;
wire [9:0] d;
wire [3:0] high;
wire [3:0] low;
wire       reset;
wire       start;
wire       stop;


// Instances 
TIMER U_0( 
   .clk   (clk), 
   .d     (d), 
   .reset (reset), 
   .start (start), 
   .stop  (stop), 
   .alarm (alarm), 
   .high  (high), 
   .low   (low)
); 

TIMER_tester U_1( 
   .alarm (alarm), 
   .high  (high), 
   .low   (low), 
   .clk   (clk), 
   .d     (d), 
   .reset (reset), 
   .start (start), 
   .stop  (stop)
); 


endmodule // TIMER_tb

